uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          FL401:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              applicationTypeDetails:
                typesOfApplication: orderApplyingFor
              withoutNoticeOrderTable:
                orderWithoutGivingNotice: orderWithout_GivingNotice
                reasonForOrderWithoutGivingNotice: orderWithoutGivingNoticeReason
                anyOtherDtailsForWithoutNoticeOrder: orderWithoutGivingNotice_moreReason
                isRespondentAlreadyInBailCondition: respondentBailConditions
                furtherDetails: situationCourtToKnow
