uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          EdgeCase:
            mandatoryFields:
              - appellant_firstName
              - appellant_lastName
              - appellant_address
              - appellant_contactNumber
              - appellant_postCode
              - appellant_email
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^([a-zA-Z0-9\\_\\-\\.]+)@([a-zA-Z0-9\\_\\-\\.]+)\\.([a-zA-Z]{2,5})$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  - appellant_postCode
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - appellant_contactNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$

