uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FL401:
            mandatoryFields:
                - appellant_firstName
                - appellant_lastName
                - appellant_address
                - telephone_number
                - orderApplyingFor
                - orderWithout_GivingNotice
            optionalFields:
              - riskOfSignificantHarm
              - deterredOrPrevented
              - deliberatelyEvadingService
              - orderWithoutGivingNotice_moreReason
              - respondentBailConditions
              - respondent_BailConditionsEndDate
              - situationCourtToKnow
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - telephone_number
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  -
                regex:

