uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          FL401:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              relationshipToRespondentTable:
                applicantRelationship: appliantRespondent_Relationship_1
                relationshipDateComplexStartDate: appliantRespondent_Relationship_StartDate
                relationshipDateComplexEndDate: appliantRespondent_Relationship_EndDate
                applicantRelationshipDate: applicantRespondent_PreviousMarried_Date
                applicantRelationshipOptions: appliantRespondent_Relationship_10
                needForParentalResponsibility: needForParentalResponsibility
              applicantsFL401:
                  firstName: applicant_firstName
                  lastName: applicant_lastName
                  email: applicant_Email
                  phoneNumber: telephone_number
              fl401StmtOfTruth:
                date: statementOfTruth_Date
                fullname: statementOfTruth_FullName
                signature:
                nameOfFirm: statementOfTruth_FirmName
                signOnBehalf: statementOfTruth_PositionHeld
              fl401RespondentTable:
                - value:
                    firstName: respondentFirstName
                    lastName: respondentLastName
                    previousName: respondentPreviousNames
                    dateOfBirth: respondentDoB
                    liveWithApplicant: respondent_LiveWithApplicant
                    phoneNumber: respondent_PhoneNumber
                    email: respondent_Email
                    address:
                          AddressLine1: respondent_Address_BuildingAndStreet
                          AddressLine2: respondent_Address_SecondLine
                          PostTown: respondent_Address_TownOrCity
                          County: respondent_Address_County
                          PostCode: respondent_Address_Postcode
              applicationTypeDetails:
                typesOfApplication: orderApplyingFor
              withoutNoticeOrderTable:
                orderWithoutGivingNotice: orderWithout_GivingNotice
                anyOtherDtailsForWithoutNoticeOrder: orderWithoutGivingNotice_moreReason
                isRespondentAlreadyInBailCondition: respondentBailConditions
                bailConditionEndDate: respondent_BailConditionsEndDate
                furtherDetails: situationCourtToKnow
              attendingTheHearingTable:
                isInterpreterNeeded: interpreterNeededAtCourt
                isDisabilityPresent: disabilitySupport_NeededAtCourt
                adjustmentsRequired: disabilitySupport_details
                specialMeasureAtCourt: specialMeasureAtCourt_Row1
                interpreterNeeds:
                  - value:
                      language: interpreterNeededAtCourt_Language
                      dialect: interpreterNeededAtCourt_Dialect
              respondentBehaviourTable:
                applicantWantToStopFromRespondentDoing:
                applicantWantToStopFromRespondentDoingToChild:
                otherReasonApplicantWantToStopFromRespondentDoing:
              fl401ApplicantTable:
                firstName: applicantFirstName
                lastName: applicantLastName
                email: applicant_Email
                previousName: applicantPreviousNames
                dateOfBirth: applicantDateOfBirth
                applicantContactInstructions: applicant_ContactInstructions
                applicantLegalRepresenationNeeded: applicant_LegalRepresenationNeeded
              fl401SolicitorDetailsTable:
                solicitorOrg:
                  OrganisationName: applicant_Solicitor_FirmName
                address:
                  addressLine1: applicant_Solicitor_Address_BuildingAndStreet
                  addressLine2: applicant_Solicitor_Address_SecondLine
                  postTown: applicant_Solicitor_Address_TownOrCity
                  county: applicant_Solicitor_Address_County
                  postCode: applicant_Solicitor_Address_Postcode
                dxNumber: applicant_Solicitor_DXNumber
                solicitorTelephone: applicant_Solicitor_PhoneNumber
                solicitorEmail: applicant_Solicitor_EmailAddress
                solicitorReference: applicant_Solicitor_Reference
              otherProceedingsTable:
                previousOrOngoingProceedings: OngoingFamilyCourtProceeding
              home:
                address:
                      AddressLine1: occupationOrderAddress_BuildingAndStreet
                      AddressLine2: occupationOrderAddress_SecondLine
                      PostTown: occupationOrderAddress_TownOrCity
                      PostCode: occupationOrderAddress_Postcode
                      County: occupationOrderAddress_County
                peopleLivingAtThisAddress: occupationOrderAddress_CurrentOccupant
                textAreaSomethingElse: occupationOrderAddress_CurrentOccupant_Others
                everLivedAtTheAddress: occupationOrderAddress_PreviousOccupant
                intendToLiveAtTheAddress: occupationOrderAddress_IntendedOccupant
                isPropertyAdapted: propertySpeciallyAdapted
                howIsThePropertyAdapted: propertySpeciallyAdapted_Details
                isThereMortgageOnProperty: MortgageOnProperty
                mortgages:
                      mortgageLenderName: MortgageLender_Name
                      address:
                            AddressLine1: MortgageLender_BuildingAndStreet
                            AddressLine2: MortgageLender_SecondLine
                            PostTown: MortgageLender_TownOrCity
                            County: MortgageLender_County
                            PostCode: MortgageLender_Postcode
                      mortgageNamedAfter:
                      textAreaSomethingElse: MortgageOnProperty_Person_Others
                      mortgageNumber: MortgageOnProperty_Number
                isPropertyRented: RentedProperty
                mortgageNamedAfterList: RentedProperty_Person
                landlords:
                      textAreaSomethingElse: RentedProperty_Person_Others
                      landlordName: LandlordDetails_Name
                      address:
                            AddressLine1: LandlordDetails_BuildingAndStreet
                            AddressLine2: LandlordDetails_SecondLine
                            PostTown: LandlordDetails_TownOrCity
                            County: LandlordDetails_County
                            PostCode: LandlordDetails_Postcode
                doesApplicantHaveHomeRights: HomeRights
                furtherInformation: CourtToConsider
