uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FL403:
            mandatoryFields:
              - solicitor_name
              - solicitor_address
              - solicitor_reference
              - solicitor_telephone_number
              - solicitor_fax_number
              - solicitor_dx_number
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                regex: dd/mm/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  - solicitor_dx_number
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - solicitor_telephone_number
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  - solicitor_fax_number
                regex: ^[0-9]{11}$