uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          C100:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              applicants:
                - value:
                    firstName: applicantOneFirstName
                    lastName: applicantOneLastName
                    previousName: applicantOnePreviousNames
                    gender: applicantOneGender
                    dateOfBirth: applicantOneDateOfBirth
                    placeOfBirth: applicantOnePlaceOfBirth
                    AddressLine1: applicantOneAddress
                    PostCode: applicantOneAddressPostCode
                    landline: applicantOneHomePhoneNumber
                    phoneNumber: applicantOneMobilePhoneNumber
                    email: applicantOneEmailAddress
                    isAtAddressLessThan5Years: hasapplicantOneLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: applicantOneAllAddressesForLastFiveYears
                    doTheyHaveLegalRepresentation: doYouHaveSolicitor
                    representativeFirstName: your_solicitor_name
                    solicitorOrg:
                      - value:
                          OrganisationName: solicitor_firm_name
                    solicitorAddress:
                      - value:
                          AddressLine1: solicitor_address
                          PostCode: solicitor_postcode
                    solicitorTelephone: solicitor_telephone_number
                    solicitorFaxNumber: solicitor_fax_number
                    dxNumber: solicitor_dx_number
                    solicitorReference: solicitor_reference
                    solicitorFeeAccount: solicitor_fee_account_No
                    solicitorEmail: solicitor_email_address
                - value:
                    firstName: applicantTwoFirstName
                    lastName: applicantTwoLastName
                    previousName: applicantTwoPreviousNames
                    gender: applicantTwoGender
                    dateOfBirth: applicantTwoDateOfBirth
                    placeOfBirth: applicantTwoPlaceOfBirth
                    AddressLine1: applicantTwoAddress
                    PostCode: applicantTwoAddressPostCode
                    landline: applicantTwoHomePhoneNumber
                    phoneNumber: applicantTwoMobilePhoneNumber
                    email: applicantTwoEmailAddress
                    isAtAddressLessThan5Years: hasapplicantTwoLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: applicantTwoAllAddressesForLastFiveYears
              typeOfChildArrangementsOrder: childArrangement_order
              children:
                - value:
                    firstName: child1_firstName
                    lastName: child1_lastName
                    dateOfBirth: child1_dateOfBirth
                    gender: child1_gender
                    orderAppliedFor: child1_orderAppliedFor
                    applicantsRelationshipToChild: child1_applicant1_relationship
                    respondentsRelationshipToChild: child1_respondent1_relationship
                - value:
                    firstName: child2_firstName
                    lastName: child2_lastName
                    dateOfBirth: child2_dateOfBirth
                    gender: child2_gender
                    orderAppliedFor: child2_orderAppliedFor
                    applicantsRelationshipToChild: child2_applicant1_relationship
                    respondentsRelationshipToChild: child2_respondent1_relationship
                - value:
                    firstName: child3_firstName
                    lastName: child3_lastName
                    dateOfBirth: child3_dateOfBirth
                    gender: child3_gender
                    orderAppliedFor: child3_orderAppliedFor
                    applicantsRelationshipToChild: child3_applicant1_relationship
                    respondentsRelationshipToChild: child3_respondent1_relationship
                - value:
                    firstName: child4_firstName
                    lastName: child4_lastName
                    dateOfBirth: child4_dateOfBirth
                    gender: child4_gender
                    orderAppliedFor: child4_orderAppliedFor
                    applicantsRelationshipToChild: child4_applicant1_relationship
                    respondentsRelationshipToChild: child4_respondent1_relationship
              miamPreviousAttendanceChecklist: NoMIAM_PreviousAttendenceReason
              miamOtherGroundsChecklist: NoMIAM_otherExceptions
              miamOtherGroundsChecklist1: noMIAM_otherReasons
              childrenKnownToLocalAuthority: childrenServicesAuthority
              childrenKnownToLocalAuthorityTextArea: child1_localAuthority_or_socialWorker
              childrenSubjectOfChildProtectionPlan: subject_to_childProtectionPlan
              parentalResponsibilityDetails: parentalResponsibilityDetails
              childLiveWith:  children_of_same_parent
              childrenParentsName: children_parentsName
              ordersForcedMarriageProtection: existingCase_onEmergencyProtection_Care_or_supervisioNorder
              childParentsNameCollection: child_parentsName_collection
              personWhoLivesWithChild: child_living_with_others_details
              claimingExemptionMiam: exemption_to_attend_MIAM
              familyMediatorMiam: familyMember_Intimation_on_No_MIAM
              applicantAttendedMiam: attended_MIAM
              applicationPermissionRequiredReason: permissionRequiredReason
              briefDetailsOnTheApplication: briefDetailsOnTheApplication
              havePreviousParentingPlan: havePreviousParentingPlan
              applicationPermissionRequired : askingPermissionForApplication
              isCaseUrgent : urgent_or_withoutHearing
              previousOrOngoingProceedings : previous_or_ongoingProceeding
              consentOrder : isConsentOrder
              welshLanguageRequirement : welshRequired

              miamTable:
                claimingExemptionMiam: exemption_to_attend_MIAM
                familyMediatorMiam: familyMember_Intimation_on_No_MIAM
                applicantAttendedMiam: attended_MIAM
              allegationsOfHarmOverviewTable :
                allegationsOfHarmDomesticAbuseYesNo: domesticAbuse
                allegationsOfHarmChildAbductionYesNo: childAbduction
                allegationsOfHarmChildAbuseYesNo: childAbuse
                allegationsOfHarmSubstanceAbuseYesNo : drugs_alcohol_substanceAbuse
                allegationsOfHarmOtherConcernsYesNo: otherSafety_or_welfareAbuse
              typeOfApplicationTable :
                applicationPermissionRequired : askingPermissionForApplication
              setOutReasonsBelow: null
              effortsMadeWithRespondents: respondent_effort
              doYouRequireAHearingWithReducedNotice: withoutNotice_abridged_or_informalNotice
              doYouNeedAWithoutNoticeHearing: withoutNotice_abridged_or_informalNotice
              caseUrgencyTimeAndReason: application_timetable
              reasonsForApplicationWithoutNotice: reason_for_consideration
              childAbuseDomesticHelpSought: order_direction_sought
              doYouRequireAWithoutNoticeHearing: withoutNotice_frustrateTheOrder
              c100RebuildHearingUrgency: urgency_reason
              setWithoutNoticeHearing: withoutNotice_frustrateTheOrder_reason
              otherProceedingsTable :
                previousOrOngoingProceedings : previous_or_ongoingProceeding
              otherProceedingsDetailsTable:
                - value:
                    previousOrOngoingProceedings: previous_or_ongoingProceeding
                    caseNumber: other_case_case_number
                    dateOrYear: other_case_date_or_year
                    nameOfCourt: other_case_name_of_court
                    nameOfChildrenInvolved: other_case_name_of_children
                    nameAndOffice: other_case_name_and_office
              respondents:
                - value:
                    firstName: respondentOneFirstName
                    lastName: respondentOneLastName
                    previousName: respondentOnePreviousNames
                    gender: respondentOneGender
                    dateOfBirth: respondentOneDateOfBirth
                    isDateOfBirthUnknown: respondentOneDateOfBirthDontKnow
                    placeOfBirth: respondentOnePlaceOfBirth
                    AddressLine1: respondentOneAddress
                    PostCode: respondentOneAddressPostCode
                    isAddressUnknown: respondentOneAddressDontKnow
                    landline: respondentOneHomePhoneNumber
                    phoneNumber: respondentOneMobilePhoneNumber
                    canYouProvidePhoneNumber: respondentOneMobilePhoneNumberDontKnow
                    email: respondentOneEmailAddress
                    canYouProvideEmailAddress: respondentOneEmailAddressDontKnow
                    isAtAddressLessThan5Years: respondentOneLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: respondentOneAllAddressesForLastFiveYears
                - value:
                    firstName: respondentTwoFirstName
                    lastName: respondentTwoLastName
                    previousName: respondentTwoPreviousNames
                    gender: respondentTwoGender
                    dateOfBirth: respondentTwoDateOfBirth
                    isDateOfBirthUnknown: respondentTwoDateOfBirthDontKnow
                    placeOfBirth: respondentTwoPlaceOfBirth
                    AddressLine1: respondentTwoAddress
                    PostCode: respondentTwoAddressPostCode
                    isAddressUnknown: respondentTwoAddressDontKnow
                    landline: respondentTwoHomePhoneNumber
                    phoneNumber: respondentTwoMobilePhoneNumber
                    canYouProvidePhoneNumber: respondentTwoMobilePhoneNumberDontKnow
                    email: respondentTwoEmailAddress
                    canYouProvideEmailAddress: respondentTwoEmailAddressDontKnow
                    isAtAddressLessThan5Years: respondentTwoLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: respondentTwoAllAddressesForLastFiveYears
              habitualResidentInOtherState: international_or_factorsAffectingLitigation
              habitualResidentInOtherStateGiveReason: internationalElement_Resident_of_another_state_details
              jurisdictionIssue: internationalElement_jurisdictionIssue
              jurisdictionIssueGiveReason: withoutNotice_jurisdictionIssue_details
              requestToForeignAuthority: internationalElement_request_toCentral_or_Consular_authority
              requestToForeignAuthorityGiveReason: internationalElement_request_toCentral_or_Consular_authority_details
              litigationCapacityFactors: factorAffectingLitigationCapacity
              litigationCapacityReferrals: assessmentByAdultLearningTeam
              litigationCapacityOtherFactors: factorsAffectingPersonInCourt
              otherPeopleInTheCaseTable:
                - value:
                    firstName: otherPeopleOneFirstName
                    lastName: otherPeopleOneLastName
                    previousName: otherPeopleOnePreviousName
                    gender: otherPeopleOneGender
                    dateOfBirth: otherPeopleOneDateOfBirth
                    isDateOfBirthKnown: otherPeopleOneDateOfBirthDontKnow
                    AddressLine1: otherPeopleOneAddress
                    PostCode: otherPeopleOneAddressPostCode
                    isCurrentAddressKnown: otherPeopleOneAddressDontKnow
                    relationshipToChild: otherPeopleOnerelationshipToChild
                - value:
                    firstName: otherPeopleTwoFirstName
                    lastName: otherPeopleTwoLastName
                    previousName: otherPeopleTwoPreviousName
                    gender: otherPeopleTwoGender
                    dateOfBirth: otherPeopleTwoDateOfBirth
                    isDateOfBirthKnown: otherPeopleTwoDateOfBirthDontKnow
                    AddressLine1: otherPeopleTwoAddress
                    PostCode: otherPeopleTwoAddressPostCode
                    isCurrentAddressKnown: otherPeopleTwoAddressDontKnow
                    relationshipToChild: otherPeopleTworelationshipToChild
              otherChildrenNotInTheCaseTable:
                - value:
                    fullName: otherChildren1FullName
                    DateOfBirth: otherChildren1DateOfBirth
                    DateOfBirthDontKnow: otherChildren1DateOfBirthDontKnow
                    Gender: otherChildren1Gender
                    RelationshipToApplicants: otherChildren1RelationshipToApplicants
                    RelationshipToRespondents: otherChildren1RelationshipToRespondents
                - value:
                    fullName: otherChildren2FullName
                    DateOfBirth: otherChildren2DateOfBirth
                    DateOfBirthDontKnow: otherChildren2DateOfBirthDontKnow
                    Gender: otherChildren2Gender
                    RelationshipToApplicants: otherChildren2RelationshipToApplicants
                    RelationshipToRespondents: otherChildren2RelationshipToRespondents
              #checklistSection1Completed: section1RelatingToChildCompleted
              #checklistSection2To4Completed: section2Section3Section4RelatingToMediationCompleted
              #checklistSection5To6Completed: section5Section6RelatingToApplicationReasonCompleted
              #checklistSection7Completed: section7RelatingToOtherCourtFullyCompleted
              #checklistSection8To10Completed: section8Section9Section10FactorsAffectingProceedingsCompleted
              #checklistSection11Completed: section11RelatingToApplicantCompleted
              #checklistSection12To14Completed: sections12Section13Section14RelatingToRespondentAndOthersNoticeCompleted
              #checklistSection16Completed: section16RelatingToTruthStatementCompleted
              #printFullName: printFullName
              #agreedBy: applicantSolicitorsFirmName
              #SignedDate: applicantAndApplicantsolicitorSignedDate
              #positionOrOfficeHeld: position_or_OfficeHeld
              #courtFeeConsent: courtFeeConsent
              isWelshNeeded: applicantRequiresWelsh
              isInterpreterNeeded: applicantRequiresInterpreter
              interpreterNeeds:
                - value:
                    language: applicantRequiresInterpreter_otherParty_dialect
                    otherAssistance: applicantRequiresInterpreter_otherParty_details
              isIntermediaryNeeded: applicantRequiresInterpreter_intermediaryRequired
              isSpecialArrangementsRequired: requiredSpecialAssistanceOrFacilities
              reasonsForIntermediary: applicantRequiresInterpreter_intermediaryRequired_details
              specialArrangementsRequired: requiredSpecialAssistanceOrFacilities_details
              mediatorRegistrationNumber: fmc_RegistrationNumber
              familyMediatorServiceName: family_Mediation_ServiceName
              soleTraderName: sole_TraderName
              #authorizedFamilyMediatorAddress: authorizedFamilyMediator_address
              #authorizedFamilyMediatorDate: authorizedFamilyMediator_date
