uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          C100:
            regexValidationFields:
              dateFields:
                fieldNames:
                  - applicant_dateOfBirth
                  - other_court_case_date
                  - authorised_family_mediator_signed_date
                  - respondent1_dateOfBirth
                  - respondent2_dateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - applicant_email
                  - respondent1_email
                  - respondent2_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  - case_no
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  - respondent1_postCode
                  - respondent2_postCode
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant_contactNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  -
                regex:
              xorConditionalFields:
                fieldNames:
                  - applicant_postCode,applicant_lastName
                regex: