uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FL401:
            mandatoryFields:
              - applicant_firstName
              - applicant_lastName
              - applicant_address
              - telephone_number
              - orderApplyingFor
              - orderWithout_GivingNotice
            optionalFields:
              - respondentFirstName
              - respondentLastName
              - previousName
              - respondentDoB
              - respondent_LiveWithApplicant
              - respondent_Address_BuildingAndStreet
              - respondent_Address_SecondLine
              - respondent_Address_TownOrCity
              - respondent_Address_County
              - respondent_Address_Postcode
              - respondent_PhoneNumber
              - respondent_Email
              - orderWithoutGivingNoticeReason
              - riskOfSignificantHarm
              - deterredOrPrevented
              - deliberatelyEvadingService
              - orderWithoutGivingNotice_moreReason
              - respondentBailConditions
              - respondent_BailConditionsEndDate
              - situationCourtToKnow
              - interpreterNeededAtCourt
              - interpreterNeededAtCourt_Language
              - interpreterNeededAtCourt_Dialect
              - disabilitySupport_NeededAtCourt
              - disabilitySupport_details
              - specialMeasureAtCourt_Row1
              - specialMeasureAtCourt_Row2
              - specialMeasureAtCourt_Row3
              - specialMeasureAtCourt_Row4
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - telephone_number
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  -
                regex:

