uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          A1:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              applicant:
                - value:
                    applicantFullName: applicant_full_name
                    applicantAddress: applicant_address
                    addressPostCode: applicant_postcode
                    applicantPhoneNumber: applicant_telephone_number
                    applicantDateOfBirth: applicant_dateOfBirth
                    reference: applicant_reference
