uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          A58:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              birthMotherFirstName: mother_firstName
              birthMotherLastName: mother_lastName
              birthMotherAddress: mother_address
              birthMotherNationality: mother_nationality
              birthMotherOccupation: mother_occupation
              birthFatherFirstName: father_firstName
              birthFatherLastName: father_lastName
              birthFatherAddress: father_address
              birthFatherNationality: father_nationality
              birthFatherOccupation: father_occupation
              parentalResponsibility: parental_responsibility
              parentalResponsibilityOrder: parental_responsibility_order
              otherParentFirstName: guardian_firstName
              otherParentLastName: guardian_LastName
              otherParentAddress: guardian_address
          A58_STEP_PARENT:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant:
                - value:
                    applicantFirstName: applicant1_firstName
                    applicantLastName: applicant1_lastName
                    applicantAddress: applicant1_address
                    applicantTelephoneNumber: applicant1_telephoneNumber
                    applicantRelationToChild: applicant1_relationToChild
                - value:
                    applicantFirstName: applicant2_firstName
                    applicantLastName: applicant2_lastName
                    applicantAddress: applicant2_address
                    applicantTelephoneNumber: applicant2_telephoneNumber
                    applicantRelationToChild: applicant2_relationToChild
              applicantRelationToChildFatherPartner: applicant_relationToChild_father_partner
          A58_RELINQUISHED_ADOPTION:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant:
                - value:
                    applicant1FirstName: applicant1_firstName
                    applicant1LastName: applicant1_lastName
                    applicant1Address: applicant1_address
                    applicant1TelephoneNumber: applicant1_telephoneNumber
                - value:
                    applicant2FirstName: applicant2_firstName
                    applicant2LastName: applicant2_lastName
                    applicant2Address: applicant2_address
                    applicant2TelephoneNumber: applicant2_telephoneNumber
              adoptionOrderConsent: adoption_order_consent
              adoptionOrderConsentAdvance: adoption_order_consent_advance
              adoptionOrderConsentAgency: adoption_order_consent_agency
              adoptionOrderNoConsent: adoption_order_no_consent
              courtConsentParentNotFound: court_consent_parent_not_found
              courtConsentParentLackCapacity: court_consent_parent_lack_capacity
              courtConsentChildWelfare: court_consent_child_welfare
