uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          A1:
            mandatoryFields:
              - applicant_name
              - applicant_address
              - applicant_ref
              - respondent_name
              - respondent_address
              - respondent_ref
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - applicant_email
                  - respondent_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant_telephone_no
                  - respondent_telephone_no
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$

