uk:
  gov:
    hmcts:
      dependency:
        fieldGroupDependency:
          C100:
            - groupExemptionToAttend:
              dependentFields:
                - NoMIAM_domesticViolence
                - NoMIAM_childProtectionConcerns
                - NoMIAM_Urgency
                - NoMIAM_PreviousAttendance
                - NoMIAM_otherReasons
              dependentFieldValue: "True"
              groupFieldName: exemption_to_attend_MIAM
              groupValidationValue: "Yes"
              requiredFieldCount: 1
            - NoMIAM_domesticViolence:
              dependentFields:
                - NoMIAM_DVE_arrestedForSimilarOffence
                - NoMIAM_DVE_relevantPoliceCaution
                - NoMIAM_DVE_relevantCriminalProceeding
                - NoMIAM_DVE_relevantConviction
                - NoMIAM_DVE_courtOrder
                - NoMIAM_DVE_protectionNotice
                - NoMIAM_DVE_protectiveInjunction
                - NoMIAM_DVE_NoCrossUndertakingGiven
                - NoMIAM_DVE_copyOfFactFinding
                - NoMIAM_DVE_expertEvidenceReport
                - NoMIAM_DVE_healthProfessionalReport
                - NoMIAM_DVE_ReferralHealthProfessionalReport
                - NoMIAM_DVE_memberOf_MultiAgencyRiskAssessmentConferrance_letter
                - NoMIAM_DVE_domesticViolenceAdvisor
                - NoMIAM_DVE_independentSexualViolenceAdvisor_Letter
                - NoMIAM_DVE_officerEmployed_localAuthority_letter
                - NoMIAM_DVE_domesticViolenceSupportCharity_letter
                - NoMIAM_DVE_domesticViolenceSupportCharity_refuge_letter
                - NoMIAM_DVE_publicAuthority_confirmationLetter
                - NoMIAM_DVE_secretaryOfState_letter
                - NoMIAM_DVE_evidenceFinancialMatters
              dependentFieldValue: "Yes"
              groupFieldName: NoMIAM_domesticViolence
              groupValidationValue: "True"
              requiredFieldCount: 1
            - groupNoMIAMChildProtectionConcerns:
              dependentFields:
                - NoMIAM_subjectOfEnquiries_byLocalAuthority
                - NoMIAM_subjectOfCPP_byLocalAuthority
              dependentFieldValue: "Yes"
              groupFieldName: NoMIAM_childProtectionConcerns
              groupValidationValue: "True"
              requiredFieldCount: 1
            - groupNoMIAMUrgency:
              dependentFields:
                - NoMIAM_urgency_risk_to_life_liberty_or_safety
                - NoMIAM_urgency_riskOfHarm
                - NoMIAM_urgency_risk_to_unlawfulRemoval
                - NoMIAM_urgency_risk_to_miscarriageOfJustice
                - NoMIAM_urgency_unreasonablehardship
                - NoMIAM_urgency_irretrievableProblem
                - NoMIAM_urgency_conflictWithOtherStateCourts
              dependentFieldValue: "Yes"
              groupFieldName: NoMIAM_Urgency
              groupValidationValue: "True"
              requiredFieldCount: 1
            - groupNoMIAMPreviousAttendance:
              dependentFields:
                - NoMIAM_PreviousAttendanceReason
              dependentFieldValue: "Yes"
              groupFieldName: NoMIAM_PreviousAttendance
              groupValidationValue: "True"
              requiredFieldCount: 1
            - groupNoMIAMOtherReasons:
              dependentFields:
                - NoMIAM_otherExceptions
              dependentFieldValue: "Yes"
              groupFieldName: NoMIAM_otherReasons
              groupValidationValue: "True"
              requiredFieldCount: 1
            - groupInternationalFactorsAffectingLitigationCheckbox:
              dependentFields:
                - internationalElement_Resident_of_another_state
                - internationalElement_jurisdictionIssue
                - internationalElement_request_toCentral_or_Consular_authority
                - factorAffectingLitigationCapacity
                - assessmentByAdultLearningTeam
                - factorsAffectingPersonInCourt
              dependentFieldValue: "*"
              groupFieldName: international_or_factorsAffectingLitigation
              groupValidationValue: "Yes"
              requiredFieldCount: 1
            - groupInternationalResidentOfAnotherState:
              dependentFields:
                - internationalElement_Resident_of_another_state_details
              dependentFieldValue: "*"
              groupFieldName: internationalElement_Resident_of_another_state
              groupValidationValue: "Yes"
              requiredFieldCount: 1
            - groupInternationalJurisdictionIssue:
              dependentFields:
                - withoutNotice_jurisdictionIssue_details
              dependentFieldValue: "*"
              groupFieldName: internationalElement_jurisdictionIssue
              groupValidationValue: "Yes"
              requiredFieldCount: 1
            - groupInternationalRequestCentralConsularAuthority:
              dependentFields:
                - internationalElement_request_toCentral_or_Consular_authority_details
              dependentFieldValue: "*"
              groupFieldName: internationalElement_request_toCentral_or_Consular_authority
              groupValidationValue: "Yes"
              requiredFieldCount: 1
