uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          C51:
            caseFields:
              CASE_TYPE_ID: C51
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant1FirstName: applicant1_firstName
              applicant1LastName: applicant1_lastName
              applicant1Address: applicant_address
              applicant1AddressPostCode: applicant_postCode
              applicant1PoneNumber: applicant_homeTelephoneNumber
              applicant1MobileNumber: applicant_mobileTelephoneNumber

              applicant2FirstName: applicant2_firstName
              applicant2LastName: applicant2_lastName
              applicant2Address: applicant2_address
              applicant2AddressPostCode: applicant2_postCode
              applicant2PhoneNumber: applicant2_homeTelephoneNumber
              applicant2MobileNumber: applicant2_mobileTelephoneNumber
