uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          A58:
            mandatoryFields:
              - applicant1_firstName
              - applicant1_lastName
              - applicant1_address
              - applicant1_telephoneNumber
            mandatoryGroupFiled:
              group:
                - child_noLaOrParentalResponsibility
                - child_LaOrParentalResponsibilityDetails
                - child_localAuthorityOrVoluntaryOrganisationName
                - child_localAuthorityOrVoluntaryOrganisationAddress
                - child_localAuthorityOrVoluntaryOrganisationNotifiedDate
                - child_localAuthorityOrVoluntaryOrganisationContactName
                - child_localAuthorityOrVoluntaryOrganisationTelephoneNo
                - child_localAuthorityOrVoluntaryOrganisationEmail
            optionalFields:
              - applicant1_relationToChild
              - applicant2_firstName
              - applicant2_lastName
              - applicant2_address
              - applicant2_telephoneNumber
              - applicant2_relationToChild
              - applicant_relationToChild_father_partner
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant1_telephoneNumber
                  - applicant2_telephoneNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
          A58_STEP_PARENT:
            mandatoryFields:
              - applicant1_firstName
              - applicant1_lastName
              - applicant1_address
              - applicant1_telephoneNumber
            optionalFields:
              - applicant1_relationToChild
              - applicant2_firstName
              - applicant2_lastName
              - applicant2_address
              - applicant2_telephoneNumber
              - applicant2_relationToChild
              - applicant_relationToChild_father_partner
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant1_telephoneNumber
                  - applicant2_telephoneNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
          A58_RELINQUISHED:
            mandatoryFields:
              - applicant1_firstName
              - applicant1_lastName
              - applicant1_address
              - applicant1_telephoneNumber
            optionalFields:
              - applicant1_relationToChild
              - applicant2_firstName
              - applicant2_lastName
              - applicant2_address
              - applicant2_telephoneNumber
              - applicant2_relationToChild
              - applicant_relationToChild_father_partner
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant1_telephoneNumber
                  - applicant2_telephoneNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
