uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          FL401:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              typeOfApplicationOrders:
                orderType:
              orderWithoutGivingNoticeToRespondent:
                orderWithoutGivingNotice: orderWithout_GivingNotice
              reasonForOrderWithoutGivingNotice:
                reasonForOrderWithoutGivingNotice:
                futherDetails: orderWithoutGivingNotice_moreReason
              bailDetails:
                isRespondentAlreadyInBailCondition: respondentBailConditions
                bailConditionEndDate:
              anyOtherDtailsForWithoutNoticeOrder:
                otherDetails: situationCourtToKnow

              applicantsFL401:
                  firstName: applicantFirstName
                  lastName: applicantLastName
                  previousName: applicantPreviousNames
                  email: applicant_Email
                  phoneNumber: applicant_PhoneNumber
                  isAddressConfidential:
                  isPhoneNumberConfidential:
                  isEmailAddressConfidential:
                  applicantPreferredContact:
                  doTheyHaveLegalRepresentation: applicant_LegalRepresenationNeeded
                  solicitorTelephone: applicant_Solicitor_PhoneNumber
                  solicitorEmail: applicant_Solicitor_EmailAddress
                  solicitorReference: applicant_Solicitor_Reference
                  dxNumber: applicant_Solicitor_DXNumber
                  applicantContactInstructions: applicant_ContactInstructions
                  address:
                    addressLine1: applicant_Address_BuildingAndStreet
                    addressLine2: applicant_Address_SecondLine
                    postTown: applicant_Address_TownOrCity
                    county: applicant_Address_County
                    postCode: applicant_Address_Postcode
                  solicitorAddress:
                      addressLine1: applicant_Solicitor_Address_BuildingAndStreet
                      addressLine2: applicant_Solicitor_Address_SecondLine
                      postTown: applicant_Solicitor_Address_TownOrCity
                      county: applicant_Solicitor_Address_County
                      postCode: applicant_Solicitor_Address_Postcode

#              fl401ApplicantTable:
#                firstName: applicantFirstName
#                lastName: applicantLastName
#                email: applicant_Email
#                previousName: applicantPreviousNames

#              fl401SolicitorDetailsTable:
#                solicitorOrg:
#                  organisationName: applicant_Solicitor_FirmName
#                dxNumber: applicant_Solicitor_DXNumber
#                solicitorTelephone: applicant_Solicitor_PhoneNumber
#                solicitorEmail: applicant_Solicitor_EmailAddress
#                solicitorReference: applicant_Solicitor_Reference

              respondentsFL401:
                firstName: respondentFirstName
                lastName: respondentLastName
                previousName: respondentPreviousNames
                email: respondent_Email
                phoneNumber: respondent_PhoneNumber
                address:
                  addressLine1: respondent_Address_BuildingAndStreet
                  addressLine2: respondent_Address_SecondLine
                  postTown: respondent_Address_TownOrCity
                  county: respondent_Address_County
                  postCode: respondent_Address_Postcode
#              fl401RespondentTable:
#                firstName: respondentFirstName
#                lastName: respondentLastName
#                previousName: respondentPreviousNames
#                dateOfBirth: respondentDoB
#                isRespondentLiveWithApplicant: respondent_LiveWithApplicant
#                phoneNumber: respondent_PhoneNumber
#                email: respondent_Email
#                address:
#                  addressLine1: respondent_Address_BuildingAndStreet
#                  addressLine2: respondent_Address_SecondLine
#                  postTown: respondent_Address_TownOrCity
#                  county: respondent_Address_County
#                  postCode: respondent_Address_Postcode

              respondentRelationDateInfoObject:

#              relationshipToRespondentTable:
#                applicantRelationship: appliantRespondent_Relationship_1
#                relationshipDateComplexStartDate: appliantRespondent_Relationship_StartDate
#                relationshipDateComplexEndDate: appliantRespondent_Relationship_EndDate
#                applicantRelationshipDate: applicantRespondent_PreviousMarried_Date
#                applicantRelationshipOptions: appliantRespondent_Relationship_10

              fl401StmtOfTruth:
                date: statementOfTruth_Date
                fullname: statementOfTruth_FullName
                signature:
                nameOfFirm: statementOfTruth_FirmName
                signOnBehalf: statementOfTruth_PositionHeld

              applicationTypeDetails:
                typesOfApplication: orderApplyingFor_nonmolestation

#              withoutNoticeOrderTable:
#                orderWithoutGivingNotice: orderWithout_GivingNotice
#                anyOtherDtailsForWithoutNoticeOrder: orderWithoutGivingNotice_moreReason
#                isRespondentAlreadyInBailCondition: respondentBailConditions
#                bailConditionEndDate: respondent_BailConditionsEndDate
#                futherDetails: situationCourtToKnow
#              attendingTheHearingTable:
#                isInterpreterNeeded: interpreterNeededAtCourt
#                isDisabilityPresent: disabilitySupport_NeededAtCourt
#                adjustmentsRequired: disabilitySupport_details
                #specialMeasureAtCourt: specialMeasureAtCourt_Row1
                #interpreterNeeds:
#              respondentBehaviourTable:
#                applicantWantToStopFromRespondentDoing:
#                applicantWantToStopFromRespondentDoingToChild:
#                otherReasonApplicantWantToStopFromRespondentDoing:
#
#              otherProceedingsTable:
#                previousOrOngoingProceedings: OngoingFamilyCourtProceeding

              isInterpreterNeeded: InterpreterNeededAtCourt
              isDisabilityPresent: disabilitySupport_NeededAtCourt

              home:
                address:
                      addressLine1: occupationOrderAddress_BuildingAndStreet
                      addressLine2: occupationOrderAddress_SecondLine
                      postTown: occupationOrderAddress_TownOrCity
                      postCode: occupationOrderAddress_Postcode
                      county: occupationOrderAddress_County
                peopleLivingAtThisAddress: occupationOrderAddress_CurrentOccupant
                textAreaSomethingElse: occupationOrderAddress_CurrentOccupant_Others
                everLivedAtTheAddress: occupationOrderAddress_PreviousOccupant
                intendToLiveAtTheAddress: occupationOrderAddress_IntendedOccupant
                isPropertyAdapted: propertySpeciallyAdapted
                howIsThePropertyAdapted: propertySpeciallyAdapted_Details
                isThereMortgageOnProperty: MortgageOnProperty
                mortgages:
                      mortgageLenderName: MortgageLender_Name
                      address:
                            addressLine1: MortgageLender_BuildingAndStreet
                            addressLine2: MortgageLender_SecondLine
                            postTown: MortgageLender_TownOrCity
                            county: MortgageLender_County
                            postCode: MortgageLender_Postcode
                      mortgageNamedAfter:
                      textAreaSomethingElse: MortgageOnProperty_Person_Others
                      mortgageNumber: MortgageOnProperty_Number
                isPropertyRented: RentedProperty
                landlords:
                      textAreaSomethingElse: RentedProperty_Person_Others
                      landlordName: LandlordDetails_Name
                      address:
                            addressLine1: LandlordDetails_BuildingAndStreet
                            addressLine2: LandlordDetails_SecondLine
                            postTown: LandlordDetails_TownOrCity
                            county: LandlordDetails_County
                            postCode: LandlordDetails_Postcode
                doesApplicantHaveHomeRights: HomeRights
                furtherInformation: CourtToConsider
