uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          A58:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant1FirstName: applicant1_firstName
              applicant1LastName: applicant1_lastName
              applicant1Address: applicant1_address
              applicant1TelephoneNumber: applicant1_telephoneNumber
              applicant1RelationToChild: applicant1_relationToChild
              applicant1DateOfBirth: applicant1_dateOfBirth
              applicant1Nationality: applicant1_nationality
              apllicant1Occupation: applicant1_occupation
              applicant2FirstName: applicant2_firstName
              applicant2LastName: applicant2_lastName
              applicant2Address: applicant2_address
              applicant2TelephoneNumber: applicant2_telephoneNumber
              applicant2RelationToChild: applicant2_relationToChild
              applicant2DateOfBirth: applicant2_dateOfBirth
              applicant2Nationality: applicant2_nationality
              apllicant2Occupation: applicant2_occupation
              solicitor:
                solicitorName: solicitor_name
                solicitorFirm: solicitor_firmName
                solicitorAddress: solicitor_address
                solicitorPhoneNumber: solicitor_telephoneNumber
                solicitorFaxNumber: solicitor_faxNumber
                solicitorDxNumber: solicitor_dxNumber
                solicitorEmail: solicitor_emailAddress
                solicitorFeeAccountNumber: solicitor_feeAccountNumber
              applicantsDomicileStatus: applicants_domicile_status
              applicantRelationToChildFatherPartner: applicant_relationToChild_father_partner
          A58_STEP_PARENT:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant:
                - value:
                    applicantFirstName: applicant1_firstName
                    applicantLastName: applicant1_lastName
                    applicantAddress: applicant1_address
                    applicantTelephoneNumber: applicant1_telephoneNumber
                    applicantRelationToChild: applicant1_relationToChild
                - value:
                    applicantFirstName: applicant2_firstName
                    applicantLastName: applicant2_lastName
                    applicantAddress: applicant2_address
                    applicantTelephoneNumber: applicant2_telephoneNumber
                    applicantRelationToChild: applicant2_relationToChild
              applicantRelationToChildFatherPartner: applicant_relationToChild_father_partner
          A58_RELINQUISHED_ADOPTION:
            caseFields:
              CASE_TYPE_ID: A58
              EVENT_ID: create-case-adop-bs
            caseDataFields:
              applicant:
                - value:
                    applicant1FirstName: applicant1_firstName
                    applicant1LastName: applicant1_lastName
                    applicant1Address: applicant1_address
                    applicant1TelephoneNumber: applicant1_telephoneNumber
                - value:
                    applicant2FirstName: applicant2_firstName
                    applicant2LastName: applicant2_lastName
                    applicant2Address: applicant2_address
                    applicant2TelephoneNumber: applicant2_telephoneNumber
              adoptionOrderConsent: adoption_order_consent
              adoptionOrderConsentAdvance: adoption_order_consent_advance
              adoptionOrderConsentAgency: adoption_order_consent_agency
              adoptionOrderNoConsent: adoption_order_no_consent
              courtConsentParentNotFound: court_consent_parent_not_found
              courtConsentParentLackCapacity: court_consent_parent_lack_capacity
              courtConsentChildWelfare: court_consent_child_welfare
