uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FL401:
            mandatoryFields:
              - applicant_firstName
              - applicant_lastName
              - applicant_address
              - telephone_number
              - orderApplyingFor
              - orderWithout_GivingNotice
            optionalFields:
              - applicantRespondent_Relationship_01
              - applicantRespondent_Relationship_02
              - applicantRespondent_Relationship_03
              - applicantRespondent_Relationship_04
              - applicantRespondent_Relationship_05
              - applicantRespondent_Relationship_06
              - applicantRespondent_Relationship_07
              - applicantRespondent_Relationship_08
              - applicantRespondent_Relationship_09
              - applicantRespondent_Relationship_StartDate
              - applicantRespondent_Relationship_EndDate
              - applicantRespondent_PreviousMarried_Date
              - applicantRespondent_Relationship_10
              - applicantRespondent_Relationship_11
              - applicantRespondent_Relationship_12
              - applicantRespondent_Relationship_13
              - applicantRespondent_Relationship_14
              - applicantRespondent_Relationship_15
              - applicantRespondent_Relationship_16
              - applicantRespondent_Relationship_17
              - applicantRespondent_Relationship_18
              - applicantRespondent_Relationship_19
              - applicantRespondent_Relationship_20
              - applicantRespondent_Relationship_21
              - applicantRespondent_Relationship_22
              - applicantRespondent_Relationship_23
              - needForParentalResponsiblity
              - respondentFirstName
              - respondentLastName
              - previousName
              - respondentDoB
              - respondent_LiveWithApplicant
              - respondent_Address_BuildingAndStreet
              - respondent_Address_SecondLine
              - respondent_Address_TownOrCity
              - respondent_Address_County
              - respondent_Address_Postcode
              - respondent_PhoneNumber
              - respondent_Email
              - orderWithoutGivingNoticeReason
              - riskOfSignificantHarm
              - deterredOrPrevented
              - deliberatelyEvadingService
              - orderWithoutGivingNotice_moreReason
              - respondentBailConditions
              - respondent_BailConditionsEndDate
              - situationCourtToKnow
              - respondentFirstName
              - respondentLastName
              - previousName
              - respondentDoB
              - respondent_LiveWithApplicant
              - respondent_Address_BuildingAndStreet
              - respondent_Address_SecondLine
              - respondent_Address_TownOrCity
              - respondent_Address_County
              - respondent_Address_Postcode
              - respondent_PhoneNumber
              - respondent_Email
              - orderWithoutGivingNoticeReason
              - riskOfSignificantHarm
              - deterredOrPrevented
              - deliberatelyEvadingService
              - orderWithoutGivingNotice_moreReason
              - respondentBailConditions
              - respondent_BailConditionsEndDate
              - situationCourtToKnow
              - interpreterNeededAtCourt
              - interpreterNeededAtCourt_Language
              - interpreterNeededAtCourt_Dialect
              - disabilitySupport_NeededAtCourt
              - disabilitySupport_details
              - specialMeasureAtCourt_Row1
              - specialMeasureAtCourt_Row2
              - specialMeasureAtCourt_Row3
              - specialMeasureAtCourt_Row4
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - telephone_number
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  -
                regex:

