uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          C51:
            mandatoryFields:
              - applicant1_firstName
              - applicant1_lastName
              - applicant_address
              - applicant_postCode
            optionalFields:
              - applicant2_firstName
              - applicant2_lastName
              - applicant_homeTelephoneNumber
              - applicant_mobileTelephoneNumber
            regexValidationFields:
              dateFields:
                fieldNames:
                  -
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  - applicant_postCode
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant_homeTelephoneNumber
                  - applicant_mobileTelephoneNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$

