uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FL403:
            mandatoryFields:
                - applicant_firstName
                - applicant_lastName
                - applicant_address
                - applicant_postcode
                - applicant_telephone_number
                - applicant_email
                - solicitor_name
                - solicitor_address
                - solicitor_reference
            regexValidationFields:
              dateFields:
                fieldNames:
                  - applicant_dateOfBirth
                regex: dd mm yy
              emailFields:
                fieldNames:
                  - applicant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  - applicant_telephone
                  - solicitor_telephone
                  - solicitor_faxNumber
                  - solicitor_dxNumber
                  - solicitor_feeAccountNumber
                regex: ^[0-9]*$

