uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          C100:
            mandatoryFields:
                - appellant_firstName
                - appellant_lastName
                - child_firstName
                - child_lastName
                - child_gender
                - appellant_childRelationship
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                regex: dd/mm/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex:
              formatFields:
                fieldNames:
                  -
                regex:
