uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          A1:
            mandatoryFields:
              - applicant_full_name
              - applicant_address
              - applicant_postcode
              - applicant_telephone_number
            optionalFields:
              - applicant_dateOfBirth
              - applicant_reference
            regexValidationFields:
              dateFields:
                fieldNames:
                  - applicant_dateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  - applicant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  - applicant_postcode
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - applicant_telephone_number
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              alphaNumericFields:
                fieldNames:
                  - applicant_ref
                regex: ^[a-zA-Z0-9]+$

