uk:
  gov:
    hmcts:
      dependency:
        fieldGroupDependency:
          FL401:
            - applyingWithoutGivingNotice:
              dependentFields:
                - riskOfSignificantHarm
                - deterredOrPrevented
                - deliberatelyEvadingService
              dependentFieldValue: "Yes"
              groupFieldName: orderWithout_GivingNotice
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "1.3 - Why do you want to apply without giving notice to the respondent?"
            - bailCondition:
              dependentFields:
                - respondent_BailConditionsEndDate
              dependentFieldValue: "*"
              groupFieldName: respondentBailConditions
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "1.6 - When do the bail conditions end?"
            - contactDetails:
              dependentFields:
                - applicant_Address_BuildingAndStreet
                - applicant_Address_TownOrCity
                - applicant_Address_Postcode
                - applicant_PhoneNumber
                - applicant_Email
                - applicant_PreferToBeContacted
              dependentFieldValue: "*"
              groupFieldName: applicantContact_Confidentiality
              groupValidationValue: "No"
              requiredFieldCount: 6
              sectionName: "2 - your details"
