uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          FGM001:
            mandatoryFields:
              - applicant_fullName
              - applicant_address
              - applicant_phoneNumber
            optionalFields:
              - optional_empty #this is just here so that optionalFields.isEmpty() in BulkScanValidationHelper
            regexValidationFields:
              dateFields:
                fieldNames:
                  regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  -
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
