uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          C100:
            mandatoryFields:
                - appellant_firstName
                - appellant_lastName
                - emergency_protection_order
            regexValidationFields:
              dateFields:
                fieldNames:
                  - appellant_dateOfBirth
                  - other_court_case_date
                  - authorised_family_mediator_signed_date
                regex: dd/mm/yyyy
              emailFields:
                fieldNames:
                  - appellant_email
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex:
