uk:
  gov:
    hmcts:
      form-group:
        formType:
          a58:
            child_placementOrderByEnglandAndWalesCourt:
              - child_placmentOrderByEnglandAndWalesCourtName
              - child_placmentOrderByEnglandAndWalesCaseNumber
              - child_placmentOrderByEnglandAndWalesTypeOfOrder
              - child_placmentOrderByEnglandAndWalesDateOfOrder
            child_freeingOrderByEnglandAndWalesCourt:
              - child_freeingOrderByEnglandAndWalesCourtName
              - child_freeingOrderByEnglandAndWalesCaseNumber
              - child_freeingOrderByEnglandAndWalesTypeOfOrder
              - child_freeingOrderByEnglandAndWalesDateOfOrder
            child_freeingOrderByNorthernIrelandCourt:
              - child_freeingOrderByNorthernIrelandCourtName
              - child_freeingOrderByNorthernIrelandCaseNumber
              - child_freeingOrderByNorthernIrelandTypeOfOrder
              - child_freeingOrderByNorthernIrelandDateOfOrder
            child_permanenceOrderByScotlandCourt:
              - child_permanenceOrderByScotlandCourtName
              - child_permanenceOrderByScotlandCaseNumber
              - child_permanenceOrderByScotlandTypeOfOrder
              - child_permanenceOrderByScotlandDateOfOrder
          a59:
            child_placementOrderByEnglandAndWalesCourt:
              - child_placmentOrderByEnglandAndWalesCourtName
              - child_placmentOrderByEnglandAndWalesCaseNumber
              - child_placmentOrderByEnglandAndWalesTypeOfOrder
              - child_placmentOrderByEnglandAndWalesDateOfOrder
            child_freeingOrderByEnglandAndWalesCourt:
              - child_freeingOrderByEnglandAndWalesCourtName
              - child_freeingOrderByEnglandAndWalesCaseNumber
              - child_freeingOrderByEnglandAndWalesTypeOfOrder
              - child_freeingOrderByEnglandAndWalesDateOfOrder
            child_freeingOrderByNorthernIrelandCourt:
              - child_freeingOrderByNorthernIrelandCourtName
              - child_freeingOrderByNorthernIrelandCaseNumber
              - child_freeingOrderByNorthernIrelandTypeOfOrder
              - child_freeingOrderByNorthernIrelandDateOfOrder
            child_permanenceOrderByScotlandCourt:
              - child_permanenceOrderByScotlandCourtName
              - child_permanenceOrderByScotlandCaseNumber
              - child_permanenceOrderByScotlandTypeOfOrder
              - child_permanenceOrderByScotlandDateOfOrder



