apiVersion: v2
appVersion: "1.0"
description: A Helm chart for family-bulk-scan-api App
name: family-bulk-scan-api
home: https://github.com/hmcts/family-bulk-scan-api
version: 0.0.8
maintainers:
  - name: HMCTS Family team
  
dependencies:
  - name: java
    version: 3.7.2
    repository: '@hmctspublic'
  - name: ccd
    version: 6.0.0
    repository: '@hmctspublic'
    tags:
        - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
